#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."
npm run lint:staged

echo "🧠 Checking TypeScript types..."
npx tsc --noEmit

echo "✅ All checks passed. Proceeding with commit."